language: python

os:
  - linux

sudo: false

cache: pip

python:
  - "3.6"
  - "3.5"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -v -e .

script:
  - 'py.test'
  - 'pycodestyle'

matrix:
  include:
    - python: "nightly"
  allow_failures:
    - python: "nightly"
  fast_finish: true


